name: GitHub Pylint on Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
   
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4 # Action to chek out code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        # Run Pylint on all Python files. The '--recursive=y' option is helpful for subdirectories.
        pylint --recursive=y .
      # You can customize the pylint command, e.g., to ignore specific errors or set a fail-under score.
      # Example with specific options:
      # pylint --disable=E0401,W0611 --fail-under=6.0 $(git ls-files '*.py')