name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
   
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Pylint
      run: |
        pip install pylint

    - name: Run Pylint with fail-under threshold
      run: >
        # This command runs pylint and will fail the job if the score is below 8.0
        pylint $(git ls-files '*.py') 
        --fail-under=9.0 
        --ignore-paths=tests/.* 
        --ignore-paths=lambdas/my-first-sam/.aws-sam/deps/.*
    
    - name: Run Tests
      run: |
        pytest tests/

    - name: Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'p/ci'

    - name: Install AWS CLI and SAM CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        pip install aws-sam-cli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Build SAM Application
      working-directory: lambdas/my-first-sam
      run: sam build

    - name: Run Checkov IaC Scan
      uses: bridgecrewio/checkov-action@v12
      with:
        framework: cloudformation
        file: lambdas/my-first-sam/template.yaml

    - name: Deploy SAM Application
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: lambdas/my-first-sam
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset